[
    {
        "name": "ps_l",
        "value": "1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1813725238.464,
        "storeId": null
    },
    {
        "name": "datr",
        "value": "AeULavHxlSDbPj3M-gm_OVdt",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1813724417.502,
        "storeId": null
    },
    {
        "name": "fr",
        "value": "0HQBXKtk3De72z56k.AWd6kNOJbVpALkiKhHlj0hFuUu32IoivmJOIugPfzJKPbWEk77s.BqC-UB..AAA.0.0.BqC-sk.AWehu7Sx_VbdNkTi8ThpGXMSNM4",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1786941987.872,
        "storeId": null
    },
    {
        "name": "vpd",
        "value": "v1%3B679x360x2",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1784349991,
        "storeId": null
    },
    {
        "name": "xs",
        "value": "49%3AzFXkKPFZJbNMjA%3A2%3A1779165154%3A-1%3A-1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1810701156.595,
        "storeId": null
    },
    {
        "name": "fbl_st",
        "value": "101231374%3BT%3A29652766",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "strict",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1810701991,
        "storeId": null
    },
    {
        "name": "locale",
        "value": "en_US",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1779769960.671,
        "storeId": null
    },
    {
        "name": "c_user",
        "value": "100090650392129",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1810701156.595,
        "storeId": null
    },
    {
        "name": "dpr",
        "value": "2",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1779769690,
        "storeId": null
    },
    {
        "name": "pas",
        "value": "100090650392129%3Aymei8X7Ut0",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1813725987.872,
        "storeId": null
    },
    {
        "name": "ps_n",
        "value": "1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1813725238.464,
        "storeId": null
    },
    {
        "name": "sb",
        "value": "AeULaou2yGDu5lN8TvhYYFXH",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1813725156.595,
        "storeId": null
    },
    {
        "name": "wl_cbv",
        "value": "v2%3Bclient_version%3A3165%3Btimestamp%3A1779165988",
        "domain": ".facebook.com",
        "ho
